apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      api: external
      service: frontend
  template:
    metadata:
      labels:
        api: external
        service: frontend
    spec:
      containers:
      - image: mahlon256/udacity-c3-frontend:local
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 64Mi
      restartPolicy: Always