version: "3"
services:
 reverseproxy:
   image: mahlon256/reverseproxy
   ports:
     - 8080:8080
   restart: always
   depends_on:
    - backend-user
    - backend-feed   
 backend-user:
  image: mahlon256/udacity-c3-restapi-user
  volumes:
   - /users/../.aws/credentials
  environment:
   POSTGRESS_USERNAME: udagramezradev
   POSTGRESS_PASSWORD: udagramezradev
   POSTGRESS_DB: udagramezradev 
   POSTGRESS_HOST: udagramezradev.ccguxurr5ary.us-east-2.rds.amazonaws.com 
   AWS_REGION: us-east-2 
   AWS_PROFILE: default 
   AWS_BUCKET: udagram-ezra-dev
   JWT_SECRET: helloworld
   URL: "http://localhost:8100"
   http.cors.enabled: "true"
   http.cors.allow-origin: http://localhost:8100
   http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
   http.cors.allow-credentials: "true"
 backend-feed:
  image: mahlon256/udacity-c3-restapi-feed
  volumes:
   - /users/../.aws/credentials
  environment:
   POSTGRESS_USERNAME: udagramezradev
   POSTGRESS_PASSWORD: udagramezradev
   POSTGRESS_DB: udagramezradev 
   POSTGRESS_HOST: udagramezradev.ccguxurr5ary.us-east-2.rds.amazonaws.com 
   AWS_REGION: us-east-2 
   AWS_PROFILE: default 
   AWS_BUCKET: udagram-ezra-dev
   JWT_SECRET: helloworld
   URL: "http://localhost:8100"
   http.cors.enabled: "true"
   http.cors.allow-origin: http://localhost:8100
   http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
   http.cors.allow-credentials: "true"
 frontend:
  image: mahlon256/udacity-c3-frontend:local
  ports:
   - "8100:80"